packages:
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - astro@6.4.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
