services:
  devenv:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ..:/home/node/whytspace-website:cached
      - pnpm-store:/home/node/.pnpm-store
    user: node
    command: sleep infinity
    # vscode automatically forwards ports, so no need to specify here
    # ports:
    #   - 3000:3000
    # disable ipv6 so that oauth flows that require loopback work correctly
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1

volumes:
  devenv:
  pnpm-store:
